// src/routes/about/+page.svelte

<style>
  .content {
    background-color: white;
    padding: 2rem;
    border-radius: 4rem;
  }

  i p {
    margin: 0;
  }

</style>

<svelte:head>
  <title>About Grif</title>
</svelte:head>

<div class='content'>

  <h1>About Grif</h1>

  <p>Hi, I'm Grif. This site is for my stuf. I like building things and annoying my friends.</p>

  <i>
    <p>"If by chance some day you're not feeling well and you should remember some</p>
    <p>silly thing I've said or done and it brings back a smile to your face or a</p>
    <p>chuckle to your heart, then my purpose as your clown has been fulfilled."</p>
  </i>
  <p>- Red Skelton</p>

  <h2>Contact Grif</h2>

  <ul>
    <li><a href='https://www.linkedin.com/in/griffin-polonus/'>LinkedIn</a></li>
    <li><a href='https://github.com/gpolonus'>GitHub</a></li>
  </ul>
</div>

// src/pages/about.jsx

import React from 'react'

export default () => (
  <div className="text-contents">
    <h1>
    about grif
    </h1>
    <p>Hi, I'm grif. This site is for my stuf. I like building things and annoying my wife and friends.</p>

    <p>
      <i>
        "If by chance some day you're not feeling well and you should remember some
        silly thing I've said or done and it brings back a smile to your face or a
        chuckle to your heart, then my purpose as your clown has been fulfilled."
      </i>
      - Red Skelton
    </p>

    <h2>
      contact grif
    </h2>
    <ul className="basic-list">
      <li>
        <a href="mailto:grif@grifstuf.com">grif@grifstuf.com</a>
      </li>
      <li>
        <a href="https://www.linkedin.com/in/griffin-polonus/">LinkedIn</a>
      </li>
      <li>
        <a href="https://github.com/gpolonus">GitHub</a>
      </li>
    </ul>
  </div>
)
